networks:
  wealthy_eater_secure_mesh:
    name: wealthy_eater_secure_mesh
    driver: bridge

volumes:
  mongodb_cluster_volume:
    driver: local
  n8n_operational_storage:
    driver: local
services:

  # Container Hub 3: Orchestration Automation Node Tool Framework
  orchestrator_n8n:
    image: docker.n8n.io/n8nio/n8n:2.23.3
    container_name: wealthy_eater_orchestrator_n8n
    networks:
      - wealthy_eater_secure_mesh
    ports:
      - "5678:5678"
    volumes:
      - n8n_operational_storage:/home/node/.n8n
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=Asia/Ho_Chi_Minh
    restart: always
